### ISSUE TITLE
Missing bower main section 

### ISSUE THREAD

**Issue by rudylacrete** [trevnorris/cbuffer#21]
The bower.json file may contain the `main` property to prevent problems with build systems who need that.
```
The primary acting files necessary to use your package. While Bower does not directly use these files, they are listed with the commands bower list --json andbower list --paths, so they can be used by build tools.
```

**Comment by trevnorris** [comment]
Fixed by https://github.com/trevnorris/cbuffer/commit/ae01dde51ba96dc859bc96b92632158d1c77a78d.
